#!/bin/bash

echo "🎉 Serena Installation Complete!"
echo "================================"
echo ""
echo "✅ What's Installed:"
echo "   📡 Serena MCP Server - Connected to Claude Code"
echo "   🤖 Agno Agent Framework - Web UI available"
echo "   🌐 Agent UI - Running on http://localhost:3000"
echo "   🔧 All dependencies and tools"
echo ""
echo "🚀 Available Commands:"
echo ""
echo "   # Start Serena Services:"
echo "   ./start_serena.sh"
echo ""
echo "   # Check Service Status:"
echo "   ./check_serena_status.sh"
echo ""
echo "   # Stop Serena Services:"
echo "   ./stop_serena.sh"
echo ""
echo "   # Use Serena in Claude Code:"
echo "   claude"
echo "   # Then type /mcp to see available tools"
echo ""
echo "🌐 Web Interface:"
echo "   Agent UI: http://localhost:3000"
echo "   (Start services first with ./start_serena.sh)"
echo ""
echo "🔧 MCP Server Status:"
echo "   claude mcp list"
echo ""
echo "📝 Next Steps:"
echo "1. Add your API keys to serena/.env:"
echo "   - ANTHROPIC_API_KEY (for Claude)"
echo "   - GOOGLE_API_KEY (for Gemini)"
echo ""
echo "2. Start the web interface:"
echo "   ./start_serena.sh"
echo ""
echo "3. Use Serena in Claude Code:"
echo "   claude"
echo "   # Type /mcp to see Serena tools"
echo ""
echo "🎯 Serena Features:"
echo "   ✅ Symbolic operations and code analysis"
echo "   ✅ File reading/writing and project management"
echo "   ✅ Code generation and refactoring"
echo "   ✅ Language server integration"
echo "   ✅ Real-time coding assistance"
echo ""
echo "📚 Documentation:"
echo "   - Serena: https://github.com/oraios/serena"
echo "   - Agno: https://agno.link"
echo "   - Claude Code MCP: https://docs.anthropic.com/en/docs/claude-code/mcp"
echo ""
echo "🎉 Enjoy coding with Serena! 🚀" 